# Generated by Django 5.2.8 on 2025-11-30 16:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_seller_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('autor', 'receptor')},
        ),
        migrations.RemoveField(
            model_name='review',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='review',
            name='tipo',
        ),
    ]
