# Generated by Django 5.2.8 on 2025-11-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tipo_venta',
            field=models.CharField(choices=[('venta', 'Solo Venta'), ('intercambio', 'Solo Intercambio'), ('ambos', 'Venta o Intercambio')], default='venta', max_length=20),
        ),
    ]
