# Generated by Django 5.2.8 on 2025-11-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='en_oferta',
            field=models.BooleanField(default=False, verbose_name='En oferta'),
        ),
        migrations.AddField(
            model_name='product',
            name='porcentaje_descuento',
            field=models.PositiveIntegerField(default=0, help_text='Descuento del 0 al 100%', verbose_name='% de descuento'),
        ),
    ]
